os: osx
git:
    submodules: true
branches:
    only:
        - master
before_install:
  - brew update && brew bundle
script:
  - hugo
cache:
  directories:
    - $HOME/Library/Caches/Homebrew
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  repo: crazygit/crazygit.github.io
  keep-history: true
  on:
    branch: master
  local_dir: public
  target_branch: master
notifications:
  slack:
    on_failure: always
    on_success: always
    rooms:
      secure: jIrgY2KOXCxTeMsEHBvxVtw/9ZQYMkyp5V9Ye0iHGva+g/b2UvRptBSG9HDKo+9JbLlhq4K2lOPnxE7AVtiqRYRyzbsIJlg3ChqfYGBWPAJt5FLzk2AQNWg4TFBltewQuGfT0Q1XvhrpsK1p5o05i2wxmcguSd36XtMndUABBiAHw87p0IBRPkQ4+jeyHax9CWo5TabXMaOgEPXYokOTZyx835NHrddcwThOxBJw8wUXA91Vds2EasMhFbwh3pdF6Xk/u6qoB1ZSWCQPKBKXXsvDeLNoFCzL+Dh37utwr0v6wOP3LTFtGY2JuaPnsx/PIxtwJaNYKd7sO53W4JG7CRbbRkrWXHlR0q9LTkbdmyODrtss0HLi94ACNFGg6+W6+F9/8i3HYhFDtqamt1HQUoDTB6tYUAe+Dl2taD0uMdbyR1HbyCBc4TT1/8bNvphMhM9cnuTZrR+vj/8cq/hF86wbCmZOf0zh4rtRSUcG+FyBuVswVprGQV3PEuXOGQLZ1VMJaihX8bhQ7rPpkqtWJ7+iRIQZGNxWqdvOzLYEWp1ByRiirX+TFXeOT15w0ZjVxoqXsgyCwb1jp8UFjaTi6DaU15JHQOjgSLjCV3wzJEaH5xo+4B7x7aFOqIgbtyH4lF/x/qs5MESYD/rm6CUV0Ioc5vkpSoBcXqF8huxfxFs=

